name: Check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: { node-version: "18", cache: "yarn" }
      - name: Prettier
        run: make prettier

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: { node-version: "18", cache: "yarn" }
      - name: Run linter
        run: make lint

  build-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: { node-version: "18", cache: "yarn" }
      - name: Build & bundle
        run: make bundle

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: { node-version: "18", cache: "yarn" }
      - name: Run tests
        run: make test
